version: '3.8'

networks:
  ils_network:
    external: true

services:
  lsa-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lsa_app_container
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=src.app
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DB=lsa
      - SECRET_KEY=773e2996b970504daadaf2625cfc07187e23035e4686aa8dade5bcb2ca190d13
    depends_on:
      - db
    volumes:
      - .:/app # Monta el código fuente local en el contenedor para recarga automática
      - /app/__pycache__/  # Evita problemas de caché en el contenedor
      - ./logs:/var/log/lsa # Monta un volumen para los logs persistentes
    networks:
      - ils_network
    command: flask run --host=0.0.0.0 --port=5000 --reload

  db:
    image: mysql:8.0
    container_name: lsa_db_container
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: lsa
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./lsa.sql:/docker-entrypoint-initdb.d/lsa.sql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - ils_network

  # New service to ensure MySQL is ready before running the SQL script
  mysql-wait:
    image: busybox
    container_name: mysql_wait_container
    entrypoint: ["sh", "-c", "until nc -z -v -w30 db 3306; do echo 'Waiting for MySQL'; sleep 5; done; echo 'MySQL is up';"]
    depends_on:
      - db
    networks:
      - ils_network

volumes:
  mysql_data:
