version: '3.8'

networks:
  ils_network:
    external: true

services:
  suite-ils-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: suite_ils_app_container
    ports:
      - "8000:80"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:l00spNiwSWpOv+1H5iOORvmPWFvrkUy2uk29O7ujNnc=
      - DB_HOST=ils_db_container
      - DB_PORT=3306
      - DB_DATABASE=sistemails
      - DB_USERNAME=root
      - DB_PASSWORD=
    volumes:
      - .:/var/www/html
      - ils_storage:/var/www/html/storage
    depends_on:
      - db
    networks:
      - ils_network

  db:
    image: mysql:8.0
    container_name: ils_db_container
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: sistemails
    ports:
      - "3308:3306"
    volumes:
      - ils_mysql_data:/var/lib/mysql
      - ./DatabaseMYSQL/sistemails.sql:/docker-entrypoint-initdb.d/sistemails.sql
    networks:
      - ils_network

  # New service to ensure MySQL is ready before running the SQL script
  mysql-wait:
    image: busybox
    container_name: mysql_wait_container
    entrypoint: ["sh", "-c", "until nc -z -v -w30 db 3306; do echo 'Waiting for MySQL'; sleep 5; done; echo 'MySQL is up';"]
    depends_on:
      - db
    networks:
      - ils_network

volumes:
  ils_mysql_data:
  ils_storage:
